QUOTES = [
    "You don't need to understand everything. You just need to understand it before the students ask",
    "Remember: Ctrl+S is not just a keyboard shortcut. It's a lifestyle",
    "Teaching computing: where half the lesson is explaining why it works and the other half is explaining why it doesn't",
    "A good programmer is someone who looks both ways before crossing a one-way street",
    "It's not a bug. It's an undocumented feature",
    "You can explain recursion to students. You just need to explain recursion first",
    "Every lesson is going perfectly until someone asks, 'Why isn't mine working?'",
    "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors",
    "If it works, don't touch it. If it doesn't work, definitely don't touch it until you've saved a copy",
    "Today is a great day to remember that computers are supposed to make our lives easier",
    "The computer did exactly what you told it to do. Unfortunately, you told it to do the wrong thing",
    "Teaching programming is mostly convincing people that computers are not actually psychic",
    "Debugging is just detective work where the murderer is usually you",
    "A semicolon walks into a bar. The bartender says, 'We don't serve your type'",
    "Why do programmers prefer dark mode? Because light attracts bugs",
    "There are 10 types of people in the world: those who understand binary and those who don't",
    "Why was the computer cold? It left its Windows open",
    "Why do Java developers wear glasses? Because they don't C#",
    "Why did the programmer quit their job? They didn't get arrays",
    "Why was the JavaScript developer sad? Because they didn't know how to Node",
    "Why did the computer go to the doctor? It had a virus",
    "Why did the student bring a ladder to computing? They wanted to reach the cloud",
    "What's a computer's favourite snack? Microchips",
    "Why did the database administrator leave their partner? They had too many relationships",
    "A SQL query walks into a bar, walks up to two tables and asks, 'Can I join you?'",
    "Why don't programmers like nature? It has too many bugs",
    "The best thing about teaching algorithms is knowing that eventually someone will ask, 'But why can't we just use ChatGPT?'",
    "If you're explaining something for the third time, congratulations: you're now officially a teacher",
    "Teaching computing is easy. Getting everyone to log in is the advanced topic",
    "The first rule of computer club is: have you tried turning it off and on again?",
    "Today's lesson objective: make it through registration without hearing 'My computer isn't working'",
    "Every teacher has a favourite student. It's the one whose code works first time",
    "Nothing builds character like a Year 8 student confidently deleting the thing you specifically told them not to delete",
    "There is no such thing as a quick change to a computer system",
    "Five minutes before the end of the lesson is the most dangerous time to demonstrate live code",
    "Live coding: because apparently normal teaching wasn't stressful enough",
    "Never trust a programme you haven't personally watched fail",
    "The best debugging tool is a student who asks, 'Why does that line do that?'",
    "Sometimes the most advanced computing skill is knowing when to stop clicking",
    "A student's code working on the first attempt is either a miracle or a trap",
    "If your code works first time, check whether you've accidentally written someone else's code",
    "Programming is 10% writing code and 90% wondering why the code you just wrote doesn't work",
    "Computer science: solving problems you didn't know existed in ways you didn't know were possible",
    "Teaching computing: turning caffeine into algorithms since forever",
    "Coffee is just RAM for teachers",
    "A teacher's RAM is measured in cups of coffee",
    "My code doesn't have bugs. It has surprise learning opportunities",
    "I don't make mistakes. I create debugging exercises",
    "Every error message is just the computer's way of asking for emotional support",
    "The computer says 'syntax error'. I say 'character building'",
    "Sometimes the code isn't broken. Sometimes the programmer is just creatively incorrect",
    "Keep calm and check your indentation",
    "When in doubt, print it out",
    "When really in doubt, add another print statement",
    "There is always one more bracket",
    "There is always one missing bracket",
    "The semicolon is optional until it isn't",
    "Indentation: because apparently computers need emotional boundaries",
    "Whitespace matters. Just ask Python",
    "Python doesn't bite. It just throws exceptions",
    "Exceptions are just Python's way of saying, 'I have concerns'",
    "Never underestimate the power of a well-placed print statement",
    "A variable walks into a bar. The bartender says, 'What'll it be?' The variable says, 'Whatever you assign me'",
    "A programmer's favourite place to hang out? The cache",
    "I told my computer I needed a break. It said, 'Have you tried restarting?'",
    "Today's forecast: 100% chance of unexpected behaviour",
    "The cloud is just someone else's computer",
    "Artificial intelligence is impressive. Artificial patience is what teachers really need",
    "You are not behind. You are debugging your workflow",
    "Some days you teach computing. Some days you teach basic mouse operation. Both are valid",
    "Progress is still progress, even when the programme crashes along the way",
    "You don't have to solve the whole problem today. Just find the next bug",
    "If today's lesson didn't go to plan, congratulations: you've gained real-world software development experience",
    "A failed programme is not a failed lesson",
    "Every programmer was once someone who didn't know what a variable was",
    "Every expert was once a beginner who kept asking questions",
    "The students don't need a perfect teacher. They need a teacher who keeps trying",
    "You know more than you think you do",
    "One bug at a time",
    "One lesson at a time",
    "Save your work. Drink some water. You've got this",
    "You survived another lesson. That's technically a successful deployment",
    "Your lesson may have crashed, but at least you didn't lose the database",
    "Remember: even production code started as something someone wrote while saying, 'This should work'",
    "Somewhere, a programmer is staring at the same error message as you",
    "The difference between a novice and an expert is usually just a larger collection of mistakes",
    "Computers are logical. Students are creative. Teachers get to referee",
    "Teaching computer science is preparing students for a future that hasn't been invented yet",
    "Today you are someone's favourite teacher. They just haven't told you yet",
    "Your students may forget today's lesson. They won't forget how you made them feel about learning",
    "If all else fails, blame the network",
    "If that doesn't work, blame DNS",
    "If DNS isn't involved, give it a minute. It might become involved",
    "Have you tried turning the teacher off and on again?",
    "Please wait while the teacher's brain loads",
    "Teacher.exe has stopped responding",
    "Loading lesson plan... 73%... 73%... 73%...",
    "Error 404: Motivation not found",
    "Warning: caffeine levels approaching critical",
    "System status: technically operational",
    "Today's lesson has been successfully compiled. Results may vary",
    "No bugs were harmed in the making of this lesson",
    "The lesson plan was tested successfully in an environment completely unlike the classroom",
    "Works on my machine",
    "It worked yesterday",
    "It worked five minutes ago",
    "It works if you don't look at it",
    "Have you tried turning it off and on again? Yes. No, the other thing",
    "A computer is only as smart as the person telling it what to do. Students are considerably more complicated",
]
